# Generated by Django 5.1.7 on 2025-03-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('FANTASY', 'Fantasy'), ('HORROR', 'Horror'), ('MAGIC', 'Magic'), ('MECHA', 'Mecha'), ('MYSTERY', 'Mystery'), ('PSYCHOLOGICAL', 'Psychological'), ('ROMANCE', 'Romance'), ('SCI_FI', 'Sci-Fi'), ('SLICE_OF_LIFE', 'Slice of Life'), ('SPORTS', 'Sports'), ('SUPERNATURAL', 'Supernatural'), ('THRILLER', 'Thriller'), ('HISTORICAL', 'Historical'), ('MARTIAL_ARTS', 'Martial Arts'), ('MUSIC', 'Music'), ('PARODY', 'Parody'), ('GAME', 'Game'), ('DEMONS', 'Demons'), ('SHOUNEN', 'Shounen'), ('SHOUJO', 'Shoujo'), ('SEINEN', 'Seinen'), ('JOSEI', 'Josei'), ('HAREM', 'Harem'), ('REVERSE_HAREM', 'Reverse Harem'), ('MILITARY', 'Military'), ('VAMPIRE', 'Vampire'), ('POLICE', 'Police'), ('SAMURAI', 'Samurai'), ('KIDS', 'Kids')], max_length=25)),
                ('num_ep', models.IntegerField(default=12)),
                ('completed', models.BooleanField(default='FALSE')),
            ],
        ),
    ]
