# Generated by Django 5.1.7 on 2025-03-17 05:08

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='completed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('FANTASY', 'Fantasy'), ('HORROR', 'Horror'), ('MAGIC', 'Magic'), ('MECHA', 'Mecha'), ('MYSTERY', 'Mystery'), ('PSYCHOLOGICAL', 'Psychological'), ('ROMANCE', 'Romance'), ('SCI_FI', 'Sci-Fi'), ('SLICE_OF_LIFE', 'Slice of Life'), ('SPORTS', 'Sports'), ('SUPERNATURAL', 'Supernatural'), ('THRILLER', 'Thriller'), ('HISTORICAL', 'Historical'), ('MARTIAL_ARTS', 'Martial Arts'), ('MUSIC', 'Music'), ('PARODY', 'Parody'), ('GAME', 'Game'), ('DEMONS', 'Demons'), ('SHOUNEN', 'Shounen'), ('SHOUJO', 'Shoujo'), ('SEINEN', 'Seinen'), ('JOSEI', 'Josei'), ('HAREM', 'Harem'), ('REVERSE_HAREM', 'Reverse Harem'), ('MILITARY', 'Military'), ('VAMPIRE', 'Vampire'), ('POLICE', 'Police'), ('SAMURAI', 'Samurai'), ('KIDS', 'Kids')], max_length=200),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
