# Generated by Django 5.1.7 on 2025-04-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0002_alter_anime_completed_alter_anime_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('episodes', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
