# Generated by Django 5.1.7 on 2025-04-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0003_animeimport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeimport',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='animeimport',
            name='anime_id',
            field=models.IntegerField(default=0),
        ),
    ]
