# Generated by Django 5.1.7 on 2025-04-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0004_rename_title_animeimport_name_animeimport_anime_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeimport',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
