# Generated by Django 5.1.7 on 2025-04-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0005_alter_animeimport_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeimport',
            old_name='anime_id',
            new_name='used_id',
        ),
        migrations.RemoveField(
            model_name='animeimport',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='animeimport',
            name='genre',
        ),
    ]
