# Generated by Django 5.1.7 on 2025-04-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_list', '0006_rename_anime_id_animeimport_used_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeimport',
            old_name='used_id',
            new_name='user_id',
        ),
    ]
